version: "3.3"

services:
  ecommerce-backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    container_name: ecommerce-backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./.env.development
    volumes:
      - .:/ecommerce-backend
      - /node_modules
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
