version: "3.3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db-backup:/data/db

  ecommerce-backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    container_name: ecommerce-backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./.env.production
    volumes:
      - .:/ecommerce-backend
      - /node_modules
    depends_on:
      - mongodb
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo-data:
